services:
    laravel.test:
        build:
            context: "./docker/8.3"
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: "sail-8.3/app"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "80:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
            SUPERVISOR_PHP_COMMAND: /usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
    selenium:
        image: selenium/standalone-chromium
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 7900:7900
        volumes:
            - "/dev/shm:/dev/shm"
        networks:
            - sail
networks:
    sail:
        driver: bridge
